routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Ecommerce\FrontController@index')->name('front.index');
Route::get('/product', 'Ecommerce\FrontController@product')->name('front.product');

Auth::routes();

Route::group(["prefix" => "administrator", "middleware" => "auth"], function() {
    Route::get('/home', 'HomeController@index')->name('home');
    
    Route::resource("category", "CategoryController")->except(["create", "show"]);
    Route::resource("product", "ProductController")->except(["show"]);

    Route::get("/product/bulk", "ProductController@massUploadForm")->name("product.bulk");
    Route::post('/product/bulk', 'ProductController@massUpload')->name('product.saveBulk');
});

app/Http/Controllers/Ecommerce/FrontController.php
<?php

namespace App\Http\Controllers\Ecommerce;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Product;
use App\Category;

class FrontController extends Controller
{
    public function index() {
        $products = Product::orderBy("created_at", "DESC")->paginate(10);

        return view("layouts.ecommerce.index", compact("products"));
    }

    public function product() {
        $products = Product::orderBy("created_at", "DESC")->paginate(12);
        $categories = Category::with(["child"])->withCount(["child"])->getParent()->orderBy('name', 'ASC')->get();
        
        return view('layouts.ecommerce.product', compact('products', 'categories'));
    }
}

resources/views/layouts/ecommerce/index.blade.php
@extends('layouts.ecommerce')

@section('title')
<title>DW Ecommerce - Pusat Belanja Online</title>
@endsection

@section('content')
<!--================Home Banner Area =================-->
<section class="home_banner_area">
    <div class="overlay"></div>
    <div class="banner_inner d-flex align-items-center">
        <div class="container">
            <div class="banner_content row">
                <div class="offset-lg-2 col-lg-8">
                    <h3>Fashion for
                        <br />Upcoming Winter</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore magna
                        aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
                    <a class="white_bg_btn" href="#">View Collection</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================End Home Banner Area =================-->

<!--================Hot Deals Area =================-->
<section class="hot_deals_area section_gap">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <div class="hot_deal_box">
                    <img class="img-fluid" src="{{ asset('ecommerce/img/product/hot_deals/deal1.jpg') }}" alt="">
                    <div class="content">
                        <h2>Hot Deals of this Month</h2>
                        <p>shop now</p>
                    </div>
                    <a class="hot_deal_link" href="#"></a>
                </div>
            </div>

            <div class="col-lg-6">
                <div class="hot_deal_box">
                    <img class="img-fluid" src="{{ asset('ecommerce/img/product/hot_deals/deal1.jpg') }}" alt="">
                    <div class="content">
                        <h2>Hot Deals of this Month</h2>
                        <p>shop now</p>
                    </div>
                    <a class="hot_deal_link" href="#"></a>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================End Hot Deals Area =================-->

<!--================Feature Product Area =================-->
<section class="feature_product_area section_gap">
    <div class="main_box">
        <div class="container-fluid">
            <div class="row">
                <div class="main_title">
                    <h2>Produk Terbaru</h2>
                    <p>Tampil trendi dengan kumpulan produk kekinian kami.</p>
                </div>
            </div>
            <div class="row">

                <!-- PERHATIAKAN BAGIAN INI, LOOPING DATA PRODUK -->
                @forelse($products as $product)
                <div class="col col1">
                    <div class="f_p_item">
                        <div class="f_p_img">
                            <!-- KEMUDIAN TAMPILKAN IMAGENYA DARI FOLDER /PUBLIC/STORAGE/PRODUCTS -->
                            <img class="img-fluid" src="{{ asset('storage/products/' . $product->image) }}"
                                alt="{{ $product->name }}">

                            <div class="p_icon">
                                <a href="{{ url('/product/' . $product->slug) }}">
                                    <i class="lnr lnr-cart"></i>
                                </a>
                            </div>
                        </div>

                        <!-- KETIKA PRODUK INI DIKLIK MAKA AKAN DIARAHKAN KE URL DIBAWAH -->
                        <!-- HANYA SAJA URL TERSEBUT BELUM DISEDIAKAN PADA ARTIKEL KALI INI -->
                        <a href="{{ url('/product/' . $product->slug) }}">
                            <!-- TAMPILKAN NAMA PRODUK -->
                            <h4>{{ $product->name }}</h4>
                        </a>

                        <!-- TAMPILKAN HARGA PRODUK -->
                        <h5>Rp {{ number_format($product->price) }}</h5>
                    </div>
                </div>
                @empty

                @endforelse
            </div>

            <!-- GENERATE PAGINATION UNTUK MEMBUAT NAVIGASI DATA SELANJUTNYA JIKA ADA -->
            <div class="row">
                {{ $products->links() }}
            </div>
        </div>
    </div>
</section>
<!--================End Feature Product Area =================-->
@endsection

resources/views/layouts/ecommerce/product.blade.php
@extends('layouts.ecommerce')

@section('title')
<title>Jual Produk Fashion - DW Ecommerce</title>
@endsection

@section('content')
<!--================Home Banner Area =================-->
<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="container">
            <div class="banner_content text-center">
                <h2>Jual Produk Fashion</h2>
                <div class="page_link">
                    <a href="{{ route('front.index') }}">Home</a>
                    <a href="{{ route('front.product') }}">Produk</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================End Home Banner Area =================-->

<!--================Category Product Area =================-->
<section class="cat_product_area section_gap">
    <div class="container-fluid">
        <div class="row flex-row-reverse">
            <div class="col-lg-9">
                <div class="product_top_bar">
                    <div class="left_dorp">
                        <select class="sorting">
                            <option value="1">Default sorting</option>
                            <option value="2">Default sorting 01</option>
                            <option value="4">Default sorting 02</option>
                        </select>

                        <select class="show">
                            <option value="1">Show 12</option>
                            <option value="2">Show 14</option>
                            <option value="4">Show 16</option>
                        </select>
                    </div>

                    <div class="right_page ml-auto">
                        {{ $products->links() }}
                    </div>
                </div>
                <div class="latest_product_inner row">

                    <!-- PROSES LOOPING DATA PRODUK, SAMA DENGAN CODE YANG ADDA DIHALAMAN HOME -->
                    @forelse ($products as $row)
                    <div class="col-lg-3 col-md-3 col-sm-6">
                        <div class="f_p_item">
                            <div class="f_p_img">
                                <img class="img-fluid" src="{{ asset('storage/products/' . $row->image) }}"
                                    alt="{{ $row->name }}">

                                <div class="p_icon">
                                    <a href="{{ url('/product/' . $row->slug) }}">
                                        <i class="lnr lnr-cart"></i>
                                    </a>
                                </div>
                            </div>

                            <a href="{{ url('/product/' . $row->slug) }}">
                                <h4>{{ $row->name }}</h4>
                            </a>

                            <h5>Rp {{ number_format($row->price) }}</h5>
                        </div>
                    </div>
                    @empty
                    @endforelse
                    <!-- PROSES LOOPING DATA PRODUK, SAMA DENGAN CODE YANG ADDA DIHALAMAN HOME -->
                </div>
            </div>

            <div class="col-lg-3">
                <div class="left_sidebar_area">
                    <aside class="left_widgets cat_widgets">
                        <div class="l_w_title">
                            <h3>Kategori Produk</h3>
                        </div>

                        <div class="widgets_inner">
                            <ul class="list">

                                <!-- PROSES LOOPING DATA KATEGORI -->
                                @foreach ($categories as $category)
                                <li>
                                    <!-- JIKA CHILDNYA ADA, MAKA KATEGORI INI AKAN MENG-EXPAND DATA DIBAWAHNYA -->
                                    <a
                                        href="{{ $category->child_count > 0 ? '#' : url('/category/' . $category->slug) }}">{{ $category->name }}</a>

                                    <!-- PROSES LOOPING DATA CHILD KATEGORI -->
                                    @foreach ($category->child as $child)
                                    <ul class="list">
                                        <li>
                                            <a href="{{ url('/category/' . $child->slug) }}">{{ $child->name }}</a>
                                        </li>
                                    </ul>
                                    @endforeach
                                </li>
                                @endforeach
                            </ul>
                        </div>
                    </aside>
                </div>
            </div>
        </div>

        <!-- GENERATE PAGINATION PRODUK -->
        <div class="row">
            {{ $products->links() }}
        </div>
    </div>
</section>
<!--================End Category Product Area =================-->
@endsection