routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Ecommerce\FrontController@index')->name('front.index');
Route::get('/product', 'Ecommerce\FrontController@product')->name('front.product');

Auth::routes();

Route::group(["prefix" => "administrator", "middleware" => "auth"], function() {
    Route::get('/home', 'HomeController@index')->name('home');
    
    Route::resource("category", "CategoryController")->except(["create", "show"]);
    Route::resource("product", "ProductController")->except(["show"]);

    Route::get("/product/bulk", "ProductController@massUploadForm")->name("product.bulk");
    Route::post('/product/bulk', 'ProductController@massUpload')->name('product.saveBulk');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Category extends Model
{
    protected $fillable = ["name", "parent_id", "slug"];

    // Relationship ke class induk.

    public function parent() {
        return $this->belongsTo(Category::class);
    }

    // Penamaan local scope harus diawali dengan 'scope' dan diikuti nama method yang diinginkan.

    public function scopeGetParent($query) {
        return $this->whereNull("parent_id");
    }

    // Mutator.

    public function setSlugAttribute($value) {
        $this->attributes["slug"] = Str::slug($value);
    }

    // Accessor.

    public function getNameAttribute($value) {
        return ucfirst($value);
    }

    // Relationship one to many dengan foreign key parent_id.

    public function child() {
        return $this->hasMany(Category::class, "parent_id");
    }

    public function product() {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;

class CategoryController extends Controller
{
    public function index() {
        // Eager loading.
        // Method 'parent' merupakan sebuah fungsi relationship antar table.

        $categories = Category::with(["parent"])->orderBy("created_at", "DESC")->paginate(10);
        
        // Legal scope.
        // Method 'getParent()' akan mengembalikan parents nya saja.

        $parents = Category::getParent()->orderBy("name", "ASC")->get();

        return view("categories.index", compact("categories", "parents"));
    }

    public function store(Request $request) {
        $this->validate($request, [
            "name" => "required|string|max:50|unique:categories"
        ]);

        $request->request->add(["slug" => $request->name]);

        Category::create($request->except("_token"));

        return redirect(route("category.index"))->with(["success" => "Kategori berhasil ditambahkan."]);
    }

    public function edit($id) {
        $category = Category::findOrFail($id);
        $parents = Category::getParent()->orderBy("name", "ASC")->get();

        return view('categories.edit', compact('category', 'parents'));
    }

    public function update(Request $request, $id) {
        $this->validate($request, [
            "name" => "required|string|max:50|unique:categories,name," . $id
        ]);

        $category = Category::findOrFail($id);

        $category->update([
            "name" => $request->name,
            "parent_id" => $request->parent_id
        ]);

        return redirect(route("category.index"))->with(["success" => "Kategori berhasil diperbarui."]);
    }

    public function destroy($id) {
        // Eager loading.
        // Hasil querynya akan menambahkan field baru bernama child_count dan product_count. 

        $category = Category::withCount(["child", "product"])->find($id);

        if ($category->child_count == 0 && $category->product_count == 0) {
            $category->delete();
            return redirect(route("category.index"))->with(["success" => "Kategori berhasil dihapus."]);
        }

        return redirect(route("category.index"))->with(["error" => "Kategori sedang digunakan!."]);
    }
}

resources/views/categories/edit.blade.php
@extends('layouts.admin')

@section('title')
<title>Edit Kategori</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item active">Edit Kategori</li>
    </ol>

    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-md-8 mx-auto">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Edit Kategori</h4>
                        </div>

                        <div class="card-body">
                            <form action="{{ route('category.update', $category->id) }}" method="post">
                                @csrf
                                @method('PUT')

                                <div class="form-group">
                                    <label for="name">Kategori</label>
                                    <input type="text" name="name" class="form-control" value="{{ $category->name }}"
                                        required>

                                    <p class="text-danger">{{ $errors->first('name') }}</p>
                                </div>

                                <div class="form-group">
                                    <label for="parent_id">Kategori</label>
                                    <select name="parent_id" class="form-control">
                                        <option value="">None</option>

                                        @foreach ($parents as $parent)
                                        <option value="{{ $parent->id }}"
                                            {{ $category->parent_id == $parent->id ? 'selected' : '' }}>
                                            {{ $parent->name }}
                                        </option>
                                        @endforeach
                                    </select>

                                    <p class="text-danger">{{ $errors->first('name') }}</p>
                                </div>

                                <div class="form-group">
                                    <button class="btn btn-primary btn-sm">Simpan</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.admin')

@section('title')
<title>List Kategori</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item active">Kategori</li>
    </ol>

    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">

                <div class="col-md-4">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Kategori Baru</h4>
                        </div>

                        <div class="card-body">
                            <form action="{{ route('category.store') }}" method="post">
                                @csrf

                                <div class="form-group">
                                    <label for="name">Kategori</label>

                                    <input type="text" name="name" class="form-control" placeholder="Masukkan kategori"
                                        required>

                                    <p class="text-danger">{{ $errors->first('name') }}</p>
                                </div>

                                <div class="form-group">
                                    <label for="parent_id">Kategori</label>

                                    <select name="parent_id" class="form-control">
                                        <option value="">None</option>

                                        @foreach ($parents as $parent)
                                        <option value="{{ $parent->id }}">{{ $parent->name }}</option>
                                        @endforeach
                                    </select>

                                    <p class="text-danger">{{ $errors->first('name') }}</p>
                                </div>

                                <div class="form-group">
                                    <button class="btn btn-primary btn-sm">Tambah</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">List Kategori</h4>
                        </div>

                        <div class="card-body">
                            @if (session('success'))
                            <div class="alert alert-success">{{ session('success') }}</div>
                            @endif

                            @if (session('error'))
                            <div class="alert alert-danger">{{ session('error') }}</div>
                            @endif

                            <div class="table-responsive">
                                <table class="table table-hover table-bordered">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Kategori</th>
                                            <th>Parent</th>
                                            <th>Created At</th>
                                            <th>Aksi</th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        @forelse ($categories as $category)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>

                                            <td><strong>{{ $category->name }}</strong></td>

                                            <td>{{ $category->parent ? $category->parent->name : '-' }}</td>

                                            <td>{{ $category->created_at->format('d-m-Y') }}</td>

                                            <td>
                                                <form action="{{ route('category.destroy', $category->id) }}"
                                                    method="post">

                                                    @csrf
                                                    @method('DELETE')

                                                    <a href="{{ route('category.edit', $category->id) }}"
                                                        class="btn btn-warning btn-sm">Edit</a>

                                                    <button class="btn btn-danger btn-sm">Hapus</button>
                                                </form>
                                            </td>
                                        </tr>

                                        @empty
                                        <tr>
                                            <td colspan="5" class="text-center">Tidak ada data</td>
                                        </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>

                            {!! $categories->links() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
@endsection