routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Ecommerce\FrontController@index')->name('front.index');
Route::get('/product', 'Ecommerce\FrontController@product')->name('front.product');

Auth::routes();

Route::group(["prefix" => "administrator", "middleware" => "auth"], function() {
    Route::get('/home', 'HomeController@index')->name('home');
    
    Route::resource("category", "CategoryController")->except(["create", "show"]);
    Route::resource("product", "ProductController")->except(["show"]);

    Route::get("/product/bulk", "ProductController@massUploadForm")->name("product.bulk");
    Route::post('/product/bulk', 'ProductController@massUpload')->name('product.saveBulk');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Product extends Model
{
    protected $guarded = [];

    public function category() {    
        return $this->belongsTo(Category::class);
    }

    public function getStatusLabelAttribute() {
        if ($this->status == 0) {
            return '<span class="badge badge-secondary">Draft</span>';
        }

        return '<span class="badge badge-success">Aktif</span>';
    }

    public function setSlugAttribute($value) {
        $this->attributes["slug"] = Str::slug($value);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use App\Category;
use Illuminate\Support\Str;
use File;
use App\Jobs\ProductJob;

class ProductController extends Controller
{
    public function index() {
        $products = Product::with(["category"])->orderBy("created_at", "DESC");

        if (request()->q != "") {
            $products = $products->where("name", "LIKE", "%" . request()->q . "%");
        }

        $products = $products->paginate(10);

        return view("products.index", compact("products"));
    }

    public function create() {
        $categories = Category::orderBy("name", "ASC")->get();

        return view("products.create", compact("categories"));
    }

    public function store(Request $request) {
        $this->validate($request, [
            'name' => 'required|string|max:100',
            'description' => 'required',
            'category_id' => 'required|exists:categories,id',
            'price' => 'required|integer',
            'weight' => 'required|integer',
            'image' => 'required|image|mimes:png,jpeg,jpg'
        ]);

        if ($request->hasFile("image")) {
            $file = $request->file("image");
            $filename = time() . "-" . Str::slug($request->name) . "." . $file->getClientOriginalExtension();
            $file->storeAs("public/products", $filename);

            $product = Product::create([
                'name' => $request->name,
                'slug' => $request->name,
                'category_id' => $request->category_id,
                'description' => $request->description,
                'image' => $filename,
                'price' => $request->price,
                'weight' => $request->weight,
                'status' => $request->status
            ]);

            return redirect(route('product.index'))->with(['success' => 'Produk berhasil ditambahkan.']);
        }
    }

    public function edit($id) {
        $product = Product::findOrFail($id);
        $categories = Category::orderBy("name", "DESC")->get();

        return view("products.edit", compact("product", "categories"));
    }

    public function update(Request $request, $id) {
        $this->validate($request, [
            'name' => 'required|string|max:100',
            'description' => 'required',
            'category_id' => 'required|exists:categories,id',
            'price' => 'required|integer',
            'weight' => 'required|integer',
            'image' => 'nullable|image|mimes:png,jpeg,jpg'
        ]);

        $product = Product::findOrFail($id);
        $filename = $product->image;

        if ($request->hasFile("image")) {
            $file = $request->file("image");
            $filename = time() . "-" . Str::slug($request->name) . "." . $file->getClientOriginalExtension();

            $file->storeAs("public/products", $filename);
            
            File::delete(storage_path('app/public/products/' . $product->image));
        }

        $product->update([
            'name' => $request->name,
            'description' => $request->description,
            'category_id' => $request->category_id,
            'price' => $request->price,
            'weight' => $request->weight,
            'image' => $filename
        ]);
        
        return redirect(route('product.index'))->with(['success' => 'Data produk diperbaharui.']);
    }

    public function destroy($id) {
        $product = Product::findOrFail($id);

        File::delete(storage_path("app/public/products/") . $product->image);

        $product->delete();

        return redirect(route('product.index'))->with(['success' => 'Produk berhasil dihapus.']);
    }

    public function massUploadForm() {
        $categories = Category::orderBy("name", "DESC")->get();

        return view("products.bulk", compact("categories"));
    }

    public function massUpload(Request $request) {
        $this->validate($request, [
            "category_id" => "required|exists:categories,id",
            'file' => 'required|mimes:xlsx'
        ]);

        if ($request->hasFile("file")) {
            $file = $request->file("file");
            $filename = time() . "-product." . $file->getClientOriginalExtension();
            $file->storeAs("public/uploads", $filename); 

            ProductJob::dispatch($request->category_id, $filename);

            return redirect()->back()->with(['success' => 'Upload produk dijadwalkan.']);
        }
    }
}

resources/views/products/bulk.blade.php
@extends('layouts.admin')

@section('title')
<title>Mass Upload</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item active">Product</li>
    </ol>

    <div class="container-fluid">
        <div class="animated fadeIn">

            <form action="{{ route('product.saveBulk') }}" method="post" enctype="multipart/form-data">
                @csrf

                <div class="category">
                    <div class="col-md-6 mx-auto">
                        <div class="card">
                            <div class="card-body">

                                @if (session('success'))
                                <div class="alert alert-success">{{ session('success') }}</div>
                                @endif

                                <div class="form-group">
                                    <label for="category_id">Kategori</label>

                                    <select name="category_id" class="form-control">
                                        <option value="">Pilih</option>

                                        @foreach ($categories as $category)
                                        <option value="{{ $category->id }}"
                                            {{ old('category_id') == $category->id ? 'selected' : '' }}>
                                            {{ $category->name }}
                                        </option>
                                        @endforeach
                                    </select>

                                    <p class="text-danger">{{ $errors->first('category_id') }}</p>
                                </div>

                                <div class="form-group">
                                    <label for="file">File Excel</label>

                                    <input type="file" name="file" class="form-control" value="{{ old('file') }}"
                                        required>

                                    <p class="text-danger">{{ $errors->first('file') }}</p>
                                </div>

                                <div class="form-group">
                                    <button class="btn btn-primary btn-sm">Upload</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</main>
@endsection

resources/views/products/create.blade.php
@extends('layouts.admin')

@section('title')
<title>Tambah Produk</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item active">Product</li>
    </ol>

    <div class="container-fluid">
        <div class="animated fadeIn">

            <form action="{{ route('product.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="row">
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Tambah Produk</h4>
                            </div>

                            <div class="card-body">
                                <div class="form-group">
                                    <label for="name">Nama Produk</label>
                                    <input type="text" name="name" class="form-control" value="{{ old('name') }}"
                                        required>

                                    <p class="text-danger">{{ $errors->first('name') }}</p>
                                </div>

                                <div class="form-group">
                                    <label for="description">Deskripsi</label>

                                    <textarea name="description" id="description"
                                        class="form-control">{{ old('description') }}</textarea>
                                    <p class="text-danger">{{ $errors->first('description') }}</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="card">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="status">Status</label>
                                    <select name="status" class="form-control" required>
                                        <option value="1" {{ old('status') == '1' ? 'selected' : '' }}>Publish</option>
                                        <option value="0" {{ old('status') == '0' ? 'selected' : '' }}>Draft</option>
                                    </select>
                                    <p class="text-danger">{{ $errors->first('status') }}</p>
                                </div>

                                <div class="form-group">
                                    <label for="category_id">Kategori</label>

                                    <select name="category_id" class="form-control">
                                        <option value="">Pilih</option>

                                        @foreach ($categories as $category)
                                        <option value="{{ $category->id }}"
                                            {{ old('category_id') == $category->id ? 'selected' : '' }}>
                                            {{ $category->name }}
                                        </option>
                                        @endforeach
                                    </select>
                                    <p class="text-danger">{{ $errors->first('category_id') }}</p>
                                </div>

                                <div class="form-group">
                                    <label for="price">Harga</label>
                                    <input type="number" name="price" class="form-control" value="{{ old('price') }}"
                                        required>
                                    <p class="text-danger">{{ $errors->first('price') }}</p>
                                </div>

                                <div class="form-group">
                                    <label for="weight">Berat</label>
                                    <input type="number" name="weight" class="form-control" value="{{ old('weight') }}"
                                        required>
                                    <p class="text-danger">{{ $errors->first('weight') }}</p>
                                </div>

                                <div class="form-group">
                                    <label for="image">Foto Produk</label>
                                    <input type="file" name="image" class="form-control" value="{{ old('image') }}"
                                        required>
                                    <p class="text-danger">{{ $errors->first('image') }}</p>
                                </div>

                                <div class="form-group">
                                    <button class="btn btn-primary btn-sm">Tambah</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</main>
@endsection

@section('js')
<script src="https://cdn.ckeditor.com/4.13.0/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace('description');
</script>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.admin')

@section('title')
<title>Edit Produk</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item active">Product</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">

            <!-- PASTIKAN MENGIRIMKAN ID PADA ROUTE YANG DIGUNAKAN -->
            <form action="{{ route('product.update', $product->id) }}" method="post" enctype="multipart/form-data">
                @csrf
                <!-- KARENA UPDATE MAKA KITA GUNAKAN DIRECTIVE DIBAWAH INI -->
                @method('PUT')

                <!-- FORM INI SAMA DENGAN CREATE, YANG BERBEDA HANYA ADA TAMBAHKAN VALUE UNTUK MASING-MASING INPUTAN  -->
                <div class="row">
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Edit Produk</h4>
                            </div>

                            <div class="card-body">
                                <div class="form-group">
                                    <label for="name">Nama Produk</label>
                                    <input type="text" name="name" class="form-control" value="{{ $product->name }}"
                                        required>
                                    <p class="text-danger">{{ $errors->first('name') }}</p>
                                </div>

                                <div class="form-group">
                                    <label for="description">Deskripsi</label>
                                    <textarea name="description" id="description"
                                        class="form-control">{{ $product->description }}</textarea>
                                    <p class="text-danger">{{ $errors->first('description') }}</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="card">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="status">Status</label>
                                    <select name="status" class="form-control" required>
                                        <option value="1" {{ $product->status == '1' ? 'selected' : '' }}>Publish
                                        </option>
                                        <option value="0" {{ $product->status == '0' ? 'selected' : '' }}>Draft</option>
                                    </select>

                                    <p class="text-danger">{{ $errors->first('status') }}</p>
                                </div>

                                <div class="form-group">
                                    <label for="category_id">Kategori</label>
                                    <select name="category_id" class="form-control">
                                        <option value="">Pilih</option>

                                        @foreach ($categories as $category)
                                        <option value="{{ $category->id }}"
                                            {{ $product->category_id == $category->id ? 'selected':'' }}>
                                            {{ $category->name }}
                                        </option>
                                        @endforeach
                                    </select>
                                    <p class="text-danger">{{ $errors->first('category_id') }}</p>
                                </div>

                                <div class="form-group">
                                    <label for="price">Harga</label>
                                    <input type="number" name="price" class="form-control" value="{{ $product->price }}"
                                        required>
                                    <p class="text-danger">{{ $errors->first('price') }}</p>
                                </div>

                                <div class="form-group">
                                    <label for="weight">Berat</label>
                                    <input type="number" name="weight" class="form-control"
                                        value="{{ $product->weight }}" required>
                                    <p class="text-danger">{{ $errors->first('weight') }}</p>
                                </div>

                                <!-- GAMBAR TIDAK LAGI WAJIB, JIKA DIISI MAKA GAMBAR AKAN DIGANTI, JIKA DIBIARKAN KOSONG MAKA GAMBAR TIDAK AKAN DIUPDATE -->
                                <div class="form-group">
                                    <label for="image">Foto Produk</label>
                                    <br>

                                    <!--  TAMPILKAN GAMBAR SAAT INI -->
                                    <img src="{{ asset('storage/products/' . $product->image) }}" width="100px"
                                        height="100px" alt="{{ $product->name }}">
                                    <hr>

                                    <input type="file" name="image" class="form-control">
                                    <p><strong>Biarkan kosong jika tidak ingin mengganti gambar</strong></p>
                                    <p class="text-danger">{{ $errors->first('image') }}</p>
                                </div>

                                <div class="form-group">
                                    <button class="btn btn-primary btn-sm">Update</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</main>
@endsection

@section('js')
<script src="https://cdn.ckeditor.com/4.13.0/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace('description');
</script>
@endsection

resources/views/products/index.blade.php
@extends('layouts.admin')

@section('title')
<title>List Product</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item active">Product</li>
    </ol>

    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">
                                List Product

                                <div class="float-right">
                                    <a href="{{ route('product.bulk') }}" class="btn btn-primary btn-sm">Mass
                                        Upload</a>

                                    <a href="{{ route('product.create') }}" class="btn btn-primary btn-sm">Tambah</a>
                                </div>
                            </h4>
                        </div>

                        <div class="card-body">
                            @if (session('success'))
                            <div class="alert alert-success">{{ session('success') }}</div>
                            @endif

                            @if (session('error'))
                            <div class="alert alert-danger">{{ session('error') }}</div>
                            @endif

                            <form action="{{ route('product.index') }}" method="get">
                                <div class="input-group mb-3 col-md-3 float-right">
                                    <input type="text" name="q" class="form-control" placeholder="Cari..."
                                        value="{{ request()->q }}">

                                    <div class="input-group-append">
                                        <button class="btn btn-secondary" type="button">Cari</button>
                                    </div>
                                </div>
                            </form>

                            <div class="table-responsive">
                                <table class="table table-hover table-bordered">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Produk</th>
                                            <th>Harga</th>
                                            <th>Created At</th>
                                            <th>Status</th>
                                            <th>Aksi</th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        @forelse ($products as $product)
                                        <tr>
                                            <td>
                                                <img src="{{ asset('storage/products/' . $product->image) }}"
                                                    width="100px" height="100px" alt="{{ $product->name }}">
                                            </td>

                                            <td>
                                                <strong>{{ $product->name }}</strong><br>

                                                <label>Kategori: <span
                                                        class="badge badge-info">{{ $product->category->name }}</span></label><br>

                                                <label>Berat: <span class="badge badge-info">{{ $product->weight }}
                                                        gr</span></label>
                                            </td>

                                            <td>Rp {{ number_format($product->price) }}</td>

                                            <td>{{ $product->created_at->format('d-m-Y') }}</td>

                                            <td>{!! $product->status_label !!}</td>

                                            <td>
                                                <form action="{{ route('product.destroy', $product->id) }}"
                                                    method="post">
                                                    @csrf
                                                    @method('DELETE')

                                                    <a href="{{ route('product.edit', $product->id) }}"
                                                        class="btn btn-warning btn-sm">Edit</a>

                                                    <button class="btn btn-danger btn-sm">Hapus</button>
                                                </form>
                                            </td>
                                        </tr>

                                        @empty
                                        <tr>
                                            <td colspan="6" class="text-center">Tidak ada data</td>
                                        </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>

                            {!! $products->links() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
@endsection